version: "2.1"
services:

  mysql-workbench:
  
    image: lscr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    restart: unless-stopped
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config/mysql-workbench:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
      
